# Configuration file for building this project with Travis CI
language: python
python: 
  - "2.7"
install: pip install -r REQUIREMENTS --use-mirrors
script: python manage.py test --settings=settings.travis
postgres:
  adapter: postgresql
  database: atlas_test
  username: postgres
before_script:
  - "sudo apt-get install binutils gdal-bin libproj-dev postgis"
  - "sudo apt-get install python-dev libfreetype6-dev zlib1g-dev libjpeg8-dev"
  - "sudo -u postgres bash ./scripts/create_template_postgis-debian.sh"
  - "createdb -T template_postgis atlas_test -U postgres"
branches:
  only:
    - develop
