# Configuration file for building this project with Travis CI
language: python
python: 
  - "2.7"
install: pip install -r REQUIREMENTS --use-mirrors && pip install -r REQUIREMENTS-dev --use-mirrors
#script: python manage.py harvest --apps=storybase_user  --settings=settings.travis
script: python manage.py test storybase_user storybase_story storybase_asset --settings=settings.travis
postgres:
  adapter: postgresql
  database: atlas_test
  username: postgres
before_install:
  - "sudo apt-get install gdal-bin libproj-dev postgis postgresql-9.1-postgis"
  - "sudo apt-get install openjdk-6-jdk solr-jetty" 
  - "sudo bash ./scripts/create_template_postgis-debian.sh"
before_script:
  - "sudo bash ./scripts/apply_django_patches /home/vagrant/virtualenv/python2.7/lib/python2.7/site-packages/django"
  - "fab -H localhost --set use_sudo= install_solr upgrade_to_solr3 install_solr_2155"
  - "createdb -T template_postgis atlas_test -U postgres"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
branches:
  only:
    - master
    - develop
