# Configuration file for building this project with Travis CI
language: python
python: 
  - "2.7"
jdk:
  - openjdk7
install: pip install -r requirements.txt --use-mirrors && pip install Fabric==1.4.0 --use-mirrors
script: python manage.py test storybase_messaging storybase_asset storybase_geo storybase_help storybase_story storybase_user storybase_taxonomy cmsplugin_storybase --settings=settings.travis
postgres:
  adapter: postgresql
  database: atlas_travis
  username: postgres
before_install: ./scripts/ci_before_install.sh
before_script: ./scripts/ci_before_script.sh
branches:
  only:
    - master
    - develop
